config/routes.rb
Rails.application.routes.draw do
  get 'feedbacks/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users, skip: [:registrations, :passwords, :confirmations, :unlocks, :omniauth_callbacks, :mailers, :rememberable], controllers: {
    sessions: 'admin_users/sessions',
  }

  devise_for :users, skip: [:confirmations, :unlocks, :omniauth_callbacks]

  root 'quiz_sets#index'
  resources :quiz_sets, only: [:index, :show] do
    member do
      post 'start_quiz'
      get 'score'
    end
    resources :quizzes, only: [:show] do
      member do
        post 'answer'
        get 'explanation'
      end
    end
  end

  resources :weak_quizzes, only: [:show] do
    collection do
      get 'start'
      post 'start_quiz'
      get 'score'
    end
    member do
      post 'answer'
      get 'explanation'
    end
  end

  resources :quizzes, only: [:index] do
    collection do
      get 'search'
    end
  end

  resource :mypages, only: [] do
    collection do
      get 'profile'
      get 'scores'
      patch 'update_profile'
    end
  end

  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'

  namespace :api do
    resources :ratings, only: [:create]
    get 'ratings', to: 'ratings#show'
    resources :quiz_sets, only: [:index]
  end

  resources :feedbacks, only: [:create]
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_quiz_set, only: [:show, :answer, :explanation]
  before_action :set_quiz, only: [:show, :answer, :explanation]
  layout 'quiz', only: [:show, :explanation]
  before_action :set_default_meta_tags, only: [:show, :explanation, :index]

  def index
    set_meta_tags title: 'クイズ一覧'
  end

  def show
    set_meta_tags title: 'クイズ'
    @choices = @quiz.choices

    if session[:original_quiz_ids].present?
      @total_quizzes = session[:original_quiz_ids].length
      current_quiz_index = session[:original_quiz_ids].index(@quiz.id)
      @current_quiz_number = current_quiz_index + 1 if current_quiz_index
    end
  end

  # rubocop:disable Metrics/AbcSize
  def answer
    session.delete(:user_choice)
    choice = Choice.find(params[:choice_id])
    correct = @quiz.correct_choice?(choice)

    session[:user_choice] = { choice_id: choice.id, correct: correct }

    if session[:answered_quiz_ids]&.include?(@quiz.id)
      flash[:alert] = 'クイズにはそれぞれ1回のみ回答してください。'
      redirect_to score_quiz_set_path(@quiz_set) and return
    end

    score_record = current_user.scores.find(session[:score_id])
    score_record.correct_answer += 1 if correct
    score_record.save!

    session[:answered_quiz_ids] ||= []
    session[:answered_quiz_ids] << @quiz.id

    performance_summary = UserQuizPerformanceSummary.find_or_create_by(user: current_user, quiz: @quiz)
    performance_summary.increment(:attempts)
    performance_summary.save
    if correct
      performance_summary.increment(:correct_answers)
      performance_summary.save
      performance_summary.increment(:consecutive_correct_answers)
      performance_summary.save
    else
      performance_summary.update(consecutive_correct_answers: 0)
    end

    redirect_to explanation_quiz_set_quiz_path(@quiz_set, @quiz)
  end
  # rubocop:enable Metrics/AbcSize

  def explanation
    set_meta_tags title: 'クイズ解説'
    current_quiz_id = params[:id].to_i
    if session[:quiz_ids].nil?
      flash[:alert] = '前のページに戻らないでください'
      redirect_to score_quiz_set_path(@quiz_set)
      return
    end

    @user_choice = session[:user_choice]
    @chosen_choice = Choice.find_by(id: @user_choice['choice_id'])

    session[:quiz_ids].delete(current_quiz_id)

    @next_quiz_id = session[:quiz_ids].first
    @next_quiz = Quiz.find_by(id: @next_quiz_id)
    @current_quiz_number = session[:original_quiz_ids].index(current_quiz_id) + 1
    @total_quizzes = session[:original_quiz_ids].length

    if @next_quiz.nil?
      session.delete(:quiz_ids)
    end
  end

  def search
    query = params[:query]
    page = params[:page] || 1 # デフォルトページ番号を設定
  
    if query.present?
      @quizzes = Quiz.joins(:quiz_set, :choices)
                     .where("quizzes.question LIKE :query OR quizzes.explanation LIKE :query OR quiz_sets.title LIKE :query OR (choices.text LIKE :query AND choices.correct = true)", query: "%#{query}%")
                     .distinct
                     .includes(:choices, :quiz_set)
    else
      @quizzes = Quiz.all
    end
  
    total_quizzes = @quizzes.count
    total_pages = (total_quizzes / 20.0).ceil # 1ページあたり20件
    
    render json: {
      quizzes: @quizzes.limit(20).offset((page.to_i - 1) * 20).as_json(include: { choices: { only: [:text, :correct] }, quiz_set: { only: :title } }),
      pagination: {
        total_pages: total_pages,
        current_page: page.to_i
      }
    }
  end

  private

  def set_quiz_set
    @quiz_set = QuizSet.find_by(id: params[:quiz_set_id])
    unless @quiz_set
      redirect_to(score_quiz_set_path(@quiz_set), alert: '指定されたクイズセットが見つかりません。') and return
    end
  end

  def set_quiz
    @quiz = @quiz_set.quizzes.find_by(id: params[:id])
    unless @quiz
      redirect_to(score_quiz_set_path(@quiz_set), alert: '指定されたクイズが見つかりません。') and return
    end
  end
end

app/views/quizzes/explanation.html.erb
<div class="container mx-auto px-1 sm:px-6 mt-8">
<h2 class="text-2xl font-bold text-gray-800 mb-4">クイズ解説</h2>
<div class="service-background rounded-lg shadow-md relative p-2 sm:p-10">
  <div class="bg-white bg-opacity-90 rounded-lg shadow-md p-4 sm:p-6 w-full sm:max-w-xl mx-auto">

    <p class="text-xl font-bold text-gray-800 mb-2">問題 <%= @current_quiz_number %> / <%= @total_quizzes %></p>

    <div class="flex flex-col items-center justify-center mt-4 mb-4">
      <% if @user_choice['correct'] %>
        <div class="text-green-500 px-6 py-4 rounded relative text-center" role="alert">
          <strong class="font-bold text-4xl">正解！</strong>
          <span class="block text-lg text-gray-700 mt-4">あなたの選択: &nbsp; <%= @chosen_choice.text %></span>
        </div>
      <% else %>
        <div class="text-red-700 px-6 py-4 rounded relative text-center" role="alert">
          <strong class="font-bold text-4xl">不正解...</strong>
          <span class="block text-lg text-gray-700 mt-4">あなたの選択: &nbsp; <%= @chosen_choice.text %></span>
        </div>
      <% end %>
    </div>


    <div class="bg-blue-100 p-4 rounded-lg mb-4">
      <p class="text-xl font-bold text-gray-700">問題:</p>
      <p class="text-lg text-gray-700 md:text-xl"><%= @quiz.question %></p>
    </div>

    <div class="bg-blue-100 p-4 rounded-lg mb-4">
      <p class="text-xl font-bold text-gray-700">正解:</p>
      <p class="text-lg text-gray-700 md:text-xl"><%= @quiz.correct_choice.text %></p>
    </div>

    <div class="bg-blue-100 p-4 rounded-lg mb-4">
      <p class="text-xl font-bold text-gray-700">解説:</p>
      <p class="text-lg text-gray-700 md:text-xl"><%= @quiz.explanation %></p>
    </div>

    <div class="mt-4">
    <% if @next_quiz %>
      <%= button_to '次へ', quiz_set_quiz_path(@quiz_set, @next_quiz), method: :get, class: "w-full bg-blue-500 hover:bg-blue-700 text-white md:text-xl font-bold py-2 px-4 rounded transition duration-300 ease-in-out block text-center" %>
    <% else %>
      <%= button_to 'スコアを見る', score_quiz_set_path(@quiz_set), method: :get, class: "w-full bg-blue-500 hover:bg-blue-700 text-white md:text-xl font-bold py-2 px-4 rounded transition duration-300 ease-in-out block text-center" %>
    <% end %>
  </div>
</div>

  <div id="star-rating-container" class="mx-auto max-w-xl mt-12">
    <div class="bg-white bg-opacity-90 rounded-lg shadow-md p-4 text-center">
      <div id="star-rating-root"
          data-user-id="<%= current_user.id %>"
          data-quiz-id="<%= @quiz.id %>"
          class="inline-block">
      </div>
      <p class="mt-2">このクイズに対する評価、ご気軽にどうぞ。</p>
      <p>サービス向上にご協力いただければ幸いです。</p>
    </div>
  </div>
</div>

<script src="/assets/quiz_page.js"></script>

app/views/quizzes/index.html.erb
<div class="container mx-auto px-4 py-12">
  <h1 class="text-4xl font-bold text-gray-800 mb-10 text-center">クイズ一覧</h1>

  <div id="autocomplete-root" class="mx-auto mb-6 relative">
  </div>

  <div class="mt-4">
    <%= link_to 'トップへ戻る', root_path, class: "block text-center text-blue-600 hover:underline" %>
  </div>
</div>

<script src="/assets/quizlist_page.js"></script>

app/views/quizzes/show.html.erb
<!-- クイズページ -->
<div class="container mx-auto px-1 sm:px-6 mt-8">
  <div class="service-background rounded-lg shadow-md relative p-2 sm:p-10">
    <div class="bg-white bg-opacity-90 rounded-lg shadow-md p-4 sm:p-6 w-full sm:max-w-xl mx-auto">
      <p class="text-xl font-bold text-gray-800 mb-8">問題 <%= @current_quiz_number %> / <%= @total_quizzes %></p>
      <p class="text-2xl text-gray-700 mb-8 md:mb-12"><%= @quiz.question %></p>

      <%= form_with url: answer_quiz_set_quiz_path(@quiz_set, @quiz), local: true, data: { turbo: false } do |form| %>
        <div class="grid grid-cols-1 gap-4 md:gap-6">
          <% @choices.shuffle.each do |choice| %>
            <%= button_tag choice.text, type: 'submit', name: 'choice_id', value: choice.id, class: "w-full bg-blue-500 hover:bg-blue-700 text-white text-base sm:text-lg md:text-xl lg:text-2xl font-medium py-2 px-4 rounded transition duration-300 ease-in-out" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>