config/routes.rb
Rails.application.routes.draw do
  get 'feedbacks/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users, skip: [:registrations, :passwords, :confirmations, :unlocks, :omniauth_callbacks, :mailers, :rememberable], controllers: {
    sessions: 'admin_users/sessions',
  }

  devise_for :users, skip: [:confirmations, :unlocks, :omniauth_callbacks]

  root 'quiz_sets#index'
  resources :quiz_sets, only: [:index, :show] do
    member do
      post 'start_quiz'
      get 'score'
    end
    resources :quizzes, only: [:show] do
      member do
        post 'answer'
        get 'explanation'
      end
    end
  end

  resources :weak_quizzes, only: [:show] do
    collection do
      get 'start'
      post 'start_quiz'
      get 'score'
    end
    member do
      post 'answer'
      get 'explanation'
    end
  end

  resources :quizzes, only: [:index] do
    collection do
      get 'search'
    end
  end

  resource :mypages, only: [] do
    collection do
      get 'profile'
      get 'scores'
      patch 'update_profile'
    end
  end

  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'

  namespace :api do
    resources :ratings, only: [:create]
    get 'ratings', to: 'ratings#show'
    resources :quiz_sets, only: [:index]
  end

  resources :feedbacks, only: [:create]
end

app/models/quiz_set.rb
class QuizSet < ApplicationRecord
  has_many :scores, dependent: :destroy
  has_many :quizzes, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
  accepts_nested_attributes_for :quizzes, allow_destroy: true

  # 特定のユーザーが答えたクイズの数を返す
  def answered_quizzes_count(user)
    quizzes.joins(:user_quiz_performance_summaries)
           .where(user_quiz_performance_summaries: { user_id: user.id })
           .distinct
           .count
  end

  # クイズセット内のクイズの総数
  def total_quizzes_count
    quizzes.count
  end
end

app/controllers/api/quiz_sets_controller.rb
module Api
  class QuizSetsController < ApplicationController
      skip_before_action :verify_authenticity_token

    def index
      quiz_sets = QuizSet.all
      render json: quiz_sets
    end
  end
end

app/controllers/quiz_sets_controller.rb
class QuizSetsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_quiz_set, only: [:show, :score]
  layout 'quiz', only: [:score]
  before_action :set_default_meta_tags, only: [:index, :show, :score]

  def index
    set_meta_tags title: 'トップページ'

    # Reactのアクション用に@quiz_setsを編集した
    @quiz_sets = QuizSet.all.map do |quiz_set|
      quiz_set_data = quiz_set.as_json
      if user_signed_in?
        quiz_set_data[:answered_quizzes_count] = quiz_set.answered_quizzes_count(current_user)
        quiz_set_data[:total_quizzes_count] = quiz_set.total_quizzes_count
      end
      quiz_set_data
    end
    @mastery_level = current_user.mastery_level if user_signed_in?
  end

  def show
    set_meta_tags title: 'クイズ開始'
    @total_questions = [@quiz_set.quizzes.count, 10].min
  end

  def start_quiz
    @quiz_set = QuizSet.find(params[:id])
    quiz_ids = @quiz_set.quizzes.pluck(:id).shuffle
    quiz_ids = quiz_ids.take(10) if quiz_ids.size > 10

    session[:quiz_ids] = quiz_ids
    session[:original_quiz_ids] = quiz_ids.dup
    session[:answered_quiz_ids] = []

    @score = current_user.scores.create(quiz_set: @quiz_set, correct_answer: 0)
    session[:score_id] = @score.id

    next_quiz_id = session[:quiz_ids].first
    redirect_to quiz_set_quiz_path(@quiz_set, next_quiz_id)
  end

  def score
    set_meta_tags title: 'スコア'
    @score = current_user.scores.find_by(id: session[:score_id])
    @total_quizzes = session[:original_quiz_ids].length
  end

  private

  def set_quiz_set
    @quiz_set = QuizSet.find_by(id: params[:id])
    redirect_to(quiz_sets_path, alert: '指定されたクイズセットが見つかりません。') unless @quiz_set
  end
end

app/views/quiz_sets/index.html.erb
<div class="w-full px-1 sm:px-1">

  <div class="note-background rounded-lg shadow-md relative p-2 sm:p-5 mb-6 md:mb-8">

    <!-- フラッシュメッセージ -->
    <% flash.each do |type, message| %>
      <div class="<%= type == 'alert' ? 'bg-red-100 border-red-400 text-red-700 max-w-4xl mx-auto' : 'bg-blue-100 border-blue-400 text-blue-700 max-w-4xl mx-auto' %> px-4 py-3 border rounded-lg mb-4">
        <p><%= message %></p>
      </div>
    <% end %>

    <div class="text-center md:mb-16 my-6 md:my-12 md:mb-16">
      <div class="inline-block relative">
        <div class="absolute inset-x-0 top-0 h-full bg-gradient-to-r from-green-500 to-blue-500 blur-lg"></div>
        <h1 class="relative z-10 text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold text-white tracking-wide mx-auto">
          市販薬の成分を知ってみよう
        </h1>
      </div>
    </div>

    <div id="note-react-root" data-user-signed-in="<%= user_signed_in?.to_json %>"></div>

  </div>


  <div class="service-background rounded-lg shadow-md relative lg:px-20 md:pb-10 lg:pb-20 p-2 sm:p-5">

    <h1 class="text-3xl md:text-4xl font-bold text-gray-800 mt-10 mb-10 md:mt-16 md:mb-16 text-center">ジャンル一覧</h1>

    <!-- クイズセットのリスト -->
    <div id="quiz-set-list-react-root" data-quiz-sets="<%= @quiz_sets.to_json %>" data-user-signed-in="<%= user_signed_in?.to_json %>"></div>

  </div>

  <div id="top-menu-react-root" data-mastery-level="<%= @mastery_level.to_json %>" data-user-signed-in="<%= user_signed_in?.to_json %>"></div>

</div>

<script src="/assets/top_page.js"></script>

app/views/quiz_sets/score.html.erb
<div class="container mx-auto px-1 sm:px-6 mt-8">
  <h2 class="text-2xl font-bold text-gray-800 mb-4">スコア</h2>
  <div class="service-background rounded-lg shadow-md relative p-2 sm:p-10">
    <div class="bg-white bg-opacity-90 rounded-lg shadow-md p-4 sm:p-6 w-full sm:max-w-xl mx-auto">

    <% flash.each do |type, message| %>
      <% unless type == 'feedback_notice' || type == 'feedback_alert' %>
        <div class="<%= type == 'alert' ? 'bg-red-100 border-red-400 text-red-700' : 'bg-blue-100 border-blue-400 text-blue-700' %> px-4 py-3 border rounded-lg mb-4">
          <p class="font-bold">注意</p>
          <p><%= message %></p>
        </div>
      <% end %>
    <% end %>

      <div class="p-4 rounded-lg mb-8">
        <p class="text-2xl md:text-3xl lg:text-4xl font-bold text-gray-700 mb-4 text-center">あなたのスコア: <%= @score.correct_answer %> / <%= @total_quizzes %> 問</p>
      </div>

      <div class="flex justify-center items-center mb-8">
        <p class="mr-4">スコアをシェアしよう！</p>
        <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-size="large" data-text="「クイズ！市販薬の成分」に挑戦！　<%= @quiz_set.title %>のクイズで <%= @score.correct_answer %> / 10点 を取りました！" data-url="https://www.quiz-drugingredients.com/　" data-hashtags="クイズ市販薬の成分" data-lang="ja" data-show-count="false">Tweet</a>
        <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>

      <%= link_to 'トップページへ戻る', quiz_sets_path, class: "block text-lg text-center mt-4 text-blue-600 hover:underline" %>
    </div>
  </div>

  <div class="bg-white bg-opacity-90 rounded-lg shadow-md p-4 sm:p-6 w-full sm:max-w-xl mx-auto mt-12">

    <% if flash[:feedback_notice] %>
      <div class="bg-blue-100 border-blue-400 text-blue-700 px-4 py-3 border rounded-lg mb-4 text-center">
        <p><%= flash[:feedback_notice] %></p>
      </div>
    <% elsif flash[:feedback_alert] %>
      <div class="bg-red-100 border-red-400 text-red-700 px-4 py-3 border rounded-lg mb-4 text-center">
        <p><%= flash[:feedback_alert] %></p>
      </div>
    <% end %>

    <%= form_with model: Feedback.new, url: feedbacks_path, local: true do |form| %>
      <%= form.hidden_field :quiz_set_id, value: @quiz_set.id %>
      <%= form.hidden_field :user_id, value: current_user.id %>
      <div class="mb-4">
        <%= form.text_area :content, rows: 4, placeholder: 'こちらに意見や感想を入力', class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
      </div>
      <div class="text-center mb-4">
        <p>ご利用いただきありがとうございます。</p>
        <p>サービス向上のために、あなたの意見や感想を教えてください。</p>
      </div>
      <div class="text-center">
        <%= form.submit '送信する', class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
      </div>
    <% end %>
  </div>
</div>

app/views/quiz_sets/show.html.erb
<div class="ontainer mx-auto px-1 sm:px-6 mt-8">
<h2 class="text-2xl font-bold text-gray-800 mb-4">クイズを始めよう</h2>

  <div class="service-background rounded-lg shadow-md relative p-2 sm:p-10">
    <div class="bg-white bg-opacity-90 rounded-lg shadow-md p-4 sm:p-6 w-full sm:max-w-xl mx-auto">
      <p class="text-2xl text-gray-700 mb-2">クイズの内容</p>
      <h2 class="text-5xl font-bold text-gray-800 mb-8"><%= @quiz_set.title %></h2>
      <p class="text-2xl text-gray-700 mb-8">症状: <%= @quiz_set.description %></p>
      <p class="text-2xl text-gray-700 mb-4">答えたクイズ数: <%= @quiz_set.answered_quizzes_count(current_user) %> / <%= @quiz_set.total_quizzes_count %></p>
      <p class="text-2xl text-gray-700 mb-8">出題数: 10問</p>

      <%= button_to 'クイズを始める', start_quiz_quiz_set_path(@quiz_set), method: :post, class: "w-full bg-blue-500 hover:bg-blue-700 text-white text-lg font-bold py-2 px-4 rounded transition duration-300 ease-in-out" %>

      <%= link_to 'トップへ戻る', root_path, class: "block text-center text-lg mt-4 text-blue-600 hover:underline" %>
    </div>
  </div>
</div>