config/routes.rb
Rails.application.routes.draw do
  get 'feedbacks/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users, skip: [:registrations, :passwords, :confirmations, :unlocks, :omniauth_callbacks, :mailers, :rememberable], controllers: {
    sessions: 'admin_users/sessions',
  }

  devise_for :users, skip: [:confirmations, :unlocks, :omniauth_callbacks]

  root 'quiz_sets#index'
  resources :quiz_sets, only: [:index, :show] do
    member do
      post 'start_quiz'
      get 'score'
    end
    resources :quizzes, only: [:show] do
      member do
        post 'answer'
        get 'explanation'
      end
    end
  end

  resources :weak_quizzes, only: [:show] do
    collection do
      get 'start'
      post 'start_quiz'
      get 'score'
    end
    member do
      post 'answer'
      get 'explanation'
    end
  end

  resources :quizzes, only: [:index] do
    collection do
      get 'search'
    end
  end

  resource :mypages, only: [] do
    collection do
      get 'profile'
      get 'scores'
      patch 'update_profile'
    end
  end

  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'

  namespace :api do
    resources :ratings, only: [:create]
    get 'ratings', to: 'ratings#show'
    resources :quiz_sets, only: [:index]
  end

  resources :feedbacks, only: [:create]
end

app/controllers/weak_quizzes_controller.rb
class WeakQuizzesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_quiz, only: [:show, :answer, :explanation]
  layout :choose_layout
  before_action :set_default_meta_tags, only: [:start, :show, :explanation, :score]

  def start
    set_meta_tags title: '苦手克服チャレンジ'
    @non_weak_quizzes_count = current_user.non_weak_quizzes_count
    @weak_quizzes_count = current_user.weak_quizzes_count
    @mastered_quizzes_count = current_user.mastered_quizzes_count
    @mastery_level = current_user.mastery_level

    @quiz_sets_stats = QuizSet.all.index_with { |quiz_set| current_user.quiz_set_stats(quiz_set) }

    @header_class = 'bg-green-500'
  end

  def start_quiz
    weak_quiz_ids = UserQuizPerformanceSummary.where(user: current_user)
                                              .select { |summary| summary.weak_subject? && summary.answered_twice_or_more? }
                                              .pluck(:quiz_id)
    weak_quiz_ids = weak_quiz_ids.sample(10)

    if weak_quiz_ids.size < 10
      extra_quiz_ids = Quiz.where.not(id: weak_quiz_ids).pluck(:id)
                           .sample(10 - weak_quiz_ids.size)
      weak_quiz_ids += extra_quiz_ids
    end
  
    shuffled_quiz_ids = weak_quiz_ids.shuffle
    session[:weak_quiz_ids] = shuffled_quiz_ids
    session[:original_weak_quiz_ids] = shuffled_quiz_ids.dup
    session[:weak_quiz_score] = 0
    session[:answered_quiz_ids] = []
  
    redirect_to action: :show, id: session[:weak_quiz_ids].first
  end

  def show
    set_meta_tags title: '苦手克服クイズ'
    @quiz = Quiz.find(params[:id])
    @choices = @quiz.choices

     current_quiz_id = params[:id].to_i
    current_quiz_index = session[:original_weak_quiz_ids].index(current_quiz_id)
    @current_quiz_number = current_quiz_index + 1 if current_quiz_index
    @total_quizzes = session[:original_weak_quiz_ids].size
  end


  def answer
    session.delete(:user_choice)
    choice = Choice.find(params[:choice_id])
    correct = @quiz.correct_choice?(choice)

    session[:user_choice] = { choice_id: choice.id, correct: correct }

    if session[:answered_quiz_ids]&.include?(@quiz.id)
      flash[:alert] = 'クイズにはそれぞれ1回のみ回答してください。'
      redirect_to score_weak_quizzes_path and return
    end

    if correct
      session[:weak_quiz_score] += 1
    end

    performance_summary = UserQuizPerformanceSummary.find_or_create_by(user: current_user, quiz: @quiz)
    performance_summary.increment(:attempts)
    performance_summary.save
    if correct
      performance_summary.increment(:correct_answers)
      performance_summary.save
      performance_summary.increment(:consecutive_correct_answers)
      performance_summary.save
    else
      performance_summary.update(consecutive_correct_answers: 0)
    end

    session[:answered_quiz_ids] ||= []
    session[:answered_quiz_ids] << @quiz.id
    redirect_to explanation_weak_quiz_path(@quiz)
  end

  def explanation
    set_meta_tags title: '苦手克服クイズ解説'
    current_quiz_id = params[:id].to_i

    @user_choice = session[:user_choice]
    @chosen_choice = Choice.find_by(id: @user_choice['choice_id'])

    current_quiz_index = session[:original_weak_quiz_ids].index(current_quiz_id)
    @current_quiz_number = current_quiz_index + 1 if current_quiz_index
    @total_quizzes = session[:original_weak_quiz_ids].size

    session[:weak_quiz_ids].delete(current_quiz_id)
  
    @next_quiz_id = session[:weak_quiz_ids].first
    @next_quiz = Quiz.find_by(id: @next_quiz_id)
  end

  def score
    set_meta_tags title: 'スコア'
    @score = session[:weak_quiz_score]
    @total_quizzes = session[:answered_quiz_ids].length
  end

  private

  def set_quiz
    @quiz = Quiz.find_by(id: params[:id])
    redirect_to(root_path, alert: '指定されたクイズが見つかりません。') unless @quiz
  end

  def choose_layout
    action_name == 'start' ? 'application' : 'weak_quizzes'
  end
end

app/views/weak_quizzes/explanation.html.erb
<div class="container mx-auto px-1 sm:px-6 mt-8">
  <h2 class="text-2xl font-bold text-gray-800 mb-4">クイズ解説</h2>
  <div class="service-background rounded-lg shadow-md relative p-2 sm:p-10">
    <div class="bg-white bg-opacity-90 rounded-lg shadow-md p-4 sm:p-6 w-full sm:max-w-xl mx-auto">

      <p class="text-xl font-bold text-gray-700 mb-2">問題 <%= @current_quiz_number %> / <%= @total_quizzes %></p>

      <div class="flex flex-col items-center justify-center mt-4 mb-4">
        <% if @user_choice['correct'] %>
          <div class="text-green-500 px-6 py-4 rounded relative text-center" role="alert">
            <strong class="font-bold text-4xl">正解！</strong>
            <span class="block text-lg text-gray-700 mt-4">あなたの選択: &nbsp; <%= @chosen_choice.text %></span>
          </div>
        <% else %>
          <div class="text-red-700 px-6 py-4 rounded relative text-center" role="alert">
            <strong class="font-bold text-4xl">不正解...</strong>
            <span class="block text-lg text-gray-700 mt-4">あなたの選択: &nbsp; <%= @chosen_choice.text %></span>
          </div>
        <% end %>
      </div>

      <div class="bg-blue-100 p-4 rounded-lg mb-4">
        <p class="text-xl font-bold text-gray-700">問題:</p>
        <p class="text-lg md:text-xl text-gray-700"><%= @quiz.question %></p>
      </div>

      <div class="bg-blue-100 p-4 rounded-lg mb-4">
        <p class="text-xl font-bold text-gray-700">正解:</p>
        <p class="text-lg md:text-xl text-gray-700"><%= @quiz.correct_choice.text %></p>
      </div>

      <div class="bg-blue-100 p-4 rounded-lg mb-4">
        <p class="text-xl font-bold text-gray-700">解説:</p>
        <p class="text-lg md:text-xl text-gray-700"><%= @quiz.explanation %></p>
      </div>

      <div class="mt-4">
      <% if @next_quiz %>
        <%= button_to '次のクイズへ', weak_quiz_path(@next_quiz), method: :get, class: "w-full bg-blue-500 hover:bg-blue-700 text-white md:text-xl font-bold py-2 px-4 rounded transition duration-300 ease-in-out block text-center" %>
      <% else %>
        <%= button_to 'スコアを見る', score_weak_quizzes_path, method: :get, class: "w-full bg-blue-500 hover:bg-blue-700 text-white md:text-xl font-bold py-2 px-4 rounded transition duration-300 ease-in-out block text-center" %>
      <% end %>
      </div>

    </div>

    <div id="star-rating-container" class="mx-auto max-w-xl mt-12">
      <div class="bg-white bg-opacity-90 rounded-lg shadow-md p-4 text-center">
        <div id="star-rating-root"
            data-user-id="<%= current_user.id %>"
            data-quiz-id="<%= @quiz.id %>"
            class="inline-block">
        </div>
        <p class="mt-2">このクイズに対する評価、ご気軽にどうぞ。</p>
        <p>サービス向上にご協力いただければ幸いです。</p>
      </div>
    </div>
  </div>
</div>

<script src="/assets/quiz_page.js"></script>

app/views/weak_quizzes/score.html.erb
<div class="container mx-auto px-1 sm:px-6 mt-8">
  <h2 class="text-2xl font-bold text-gray-800 mb-4">スコア</h2>
  <div class="service-background rounded-lg shadow-md relative p-2 sm:p-10">
    <div class="bg-white bg-opacity-90 rounded-lg shadow-md p-4 sm:p-6 w-full sm:max-w-xl mx-auto">

      <% flash.each do |type, message| %>
        <div class="<%= type == 'alert' ? 'bg-red-100 border-red-400 text-red-700' : 'bg-blue-100 border-blue-400 text-blue-700' %> px-4 py-3 border rounded-lg mb-4">
          <p class="font-bold">注意</p>
          <p><%= message %></p>
        </div>
      <% end %>

      <div class="p-4 rounded-lg mb-8">
        <p class="text-3xl md:text-3xl lg:text-4xl font-bold text-gray-700 mb-4 text-center">あなたのスコア: <%= @score %> / <%= @total_quizzes %> 問</p>
      </div>

      <div class="flex justify-center items-center mb-8">
        <p class="mr-4">スコアをシェアしよう！</p>
        <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-size="large" data-text="「クイズ！市販薬の成分」に挑戦！　苦手克服チャレンジで <%= @score %> / 10点 を取りました！" data-url="https://www.quiz-drugingredients.com/　" data-hashtags="クイズ市販薬の成分" data-lang="ja" data-show-count="false">Tweet</a>
        <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>

      <%= link_to '苦手克服トップに戻る', start_weak_quizzes_path, class: "block text-lg text-center text-blue-600 hover:underline" %>
    </div>
  </div>
</div>

app/views/weak_quizzes/show.html.erb
<!-- クイズページ -->
<div class="container mx-auto px-1 sm:px-6 mt-8">
  <div class="service-background rounded-lg shadow-md relative p-2 sm:p-10">
    <div class="bg-white bg-opacity-90 rounded-lg shadow-md p-4 sm:p-6 w-full sm:max-w-xl mx-auto">
      <p class="text-xl font-bold text-gray-800 mb-8">問題 <%= @current_quiz_number %> / <%= @total_quizzes %></p>
      <p class="text-2xl text-gray-800 mb-8 md:mb-12"><%= @quiz.question %></p>

      <%= form_with url: answer_weak_quiz_path(@quiz), local: true, data: { turbo: false } do |form| %>
        <div class="grid grid-cols-1 gap-4 md:gap-6">
          <% @choices.each do |choice| %>
            <%= button_tag choice.text, type: 'submit', name: 'choice_id', value: choice.id, class: "w-full bg-blue-500 hover:bg-blue-700 text-white text-base sm:text-lg md:text-xl lg:text-2xl font-medium  py-2 px-4 rounded transition duration-300 ease-in-out" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/weak_quizzes/start.html.erb
<div class="container mx-auto px-1 sm:px-6 mt-8">
  <h2 class="text-2xl font-bold text-gray-800 mb-4">苦手克服チャレンジ</h2>
  <div class="service-background rounded-lg shadow-md relative p-2 sm:p-10">
    <div class="bg-white bg-opacity-90 rounded-lg shadow-md p-4 sm:p-6 w-full sm:max-w-2xl mx-auto">
      
      <p class="text-lg font-bold text-gray-700 mb-2">苦手克服チャレンジ とは</p>
      <p class="text-lg text-gray-700 mb-2">苦手なクイズの克服にチャレンジできます！</p>
      <p class="text-lg text-gray-700 mb-2">各クイズセットにたくさん挑戦した後に取り組みましょう。</p>
      <p class="text-lg text-gray-700 mb-2  underline">2回以上回答した問題のみが、苦手、克服、定着の判定に入ります。1回以下の回答のクイズは反映されません。</p>
      <p class="text-lg text-gray-700 mb-2">苦手なクイズが10問以下の場合でもランダムでクイズが追加され必ず10問出題されますので、純粋に復習としてもお使いください。</p>
      <p class="text-lg text-gray-700 mb-2">苦手克服度100%を目指しましょう！</p>

      <div class="border-b border-gray-200 mb-4">
        <div class="flex items-center mb-2">
          <h3 class="text-2xl sm:text-4xl font-bold text-gray-800 mr-2">苦手克服度:</h3>
          <p class="text-2xl sm:text-5xl font-bold text-blue-600"><%= @mastery_level %>%</p>
        </div>
        <p class="text-lg text-gray-700">苦手克服度は、あなたが克服した苦手なクイズの割合を基に計算されます。</p>
      </div>

      <div class="border-b border-gray-200 mb-4">
        <div class="flex items-center mb-2">
          <h3 class="text-xl font-bold text-gray-800 mr-2">苦手と判定されたクイズの数:</h3>
          <p class="text-2xl font-bold text-blue-600"><%= @weak_quizzes_count %>問</p>
        </div>
        <p class="text-lg text-gray-700">苦手と判定されたクイズとは、2回以上回答していて正答率が80%以下のクイズです。</p>
      </div>

      <div class="border-b border-gray-200 mb-4">
        <div class="flex items-center mb-4">
          <h3 class="text-xl font-bold text-gray-800 mr-2">苦手を克服したクイズの数:</h3>
          <p class="text-2xl font-bold text-blue-600"><%= @mastered_quizzes_count %>問</p>
        </div>
        <p class="text-lg text-gray-700">苦手を克服したクイズとは、2回以上回答していて正答率は80%以下ですが直近で2回以上連続で正解したクイズです。</p>
      </div>

      <div class="border-b border-gray-200 mb-4">
        <div class="flex items-center mb-4">
          <h3 class="text-xl font-bold text-gray-800 mr-2">定着したクイズの数:</h3>
          <p class="text-2xl font-bold text-blue-600"><%= @non_weak_quizzes_count %>問</p>
        </div>
        <p class="text-lg text-gray-700">定着しているクイズ（2回以上回答していて正答率が80%より上）の数は苦手克服度の計算に含まれません。</p>
      </div>

      <p>出題数: 10問</p>
      <div class="mt-4">
        <%= button_to 'クイズを始める', start_quiz_weak_quizzes_path, method: :post, class: "w-full bg-blue-500 hover:bg-blue-700 text-white text-lg font-bold py-2 px-4 rounded transition duration-300 ease-in-out" %>
      </div>

      <div class="flex justify-center items-center my-6">
        <p class="mr-4">苦手克服度をシェアしよう！</p>
        <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-size="large" data-text="「クイズ！市販薬の成分」に挑戦！　苦手克服チャレンジの克服度は <%= @mastery_level %>%です！　苦手なクイズは<%= @weak_quizzes_count %>問、克服したクイズは<%= @mastered_quizzes_count %>問、定着したクイズは<%= @non_weak_quizzes_count %>問です！" data-url="https://www.quiz-drugingredients.com/　" data-hashtags="クイズ市販薬の成分" data-lang="ja" data-show-count="false">Tweet</a>
        <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>

      <div class="mt-4">
        <%= link_to 'トップへ戻る', root_path, class: "block text-center text-lg text-blue-600 hover:underline" %>
      </div>
    </div>
  </div>

  <h1 class="text-2xl sm:text-4xl font-bold text-gray-800 mt-16 mb-6 text-center">各クイズセットの回答状況</h1>

  <div class="overflow-x-auto relative shadow-base sm:rounded-lg">
    <table class="w-full text-left text-base md:text-lg ">
      <thead class="text-gray-700 uppercase bg-gray-200">
        <tr>
          <th scope="col" class="py-3 px-6 text-center">クイズセット</th>
          <th scope="col" class="py-3 px-6 text-center">総問題数</th>
          <th scope="col" class="py-3 px-6 text-center">2回以上答えた問題数</th>
          <th scope="col" class="py-3 px-6 text-center">苦手な問題数</th>
          <th scope="col" class="py-3 px-6 text-center">克服した問題数</th>
          <th scope="col" class="py-3 px-6 text-center">定着した問題数</th>
        </tr>
      </thead>
      <tbody>
        <% @quiz_sets_stats.each do |quiz_set, stats| %>
          <tr class="bg-white border-b md:text-lg">
            <th scope="row" class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap text-center">
              <%= quiz_set.title %>
            </th>
            <td class="py-4 px-6 text-center"><%= stats[:total_quizzes] %></td>
            <td class="py-4 px-6 text-center"><%= stats[:answered_twice_or_more_count] %></td>
            <td class="py-4 px-6 text-center"><%= stats[:weak_quizzes_count] %></td>
            <td class="py-4 px-6 text-center"><%= stats[:mastered_quizzes_count] %></td>
            <td class="py-4 px-6 text-center"><%= stats[:non_weak_quizzes_count] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<% content_for :footer do %>
  <%= render 'layouts/footer' %>
<% end %>