config/routes.rb
Rails.application.routes.draw do
  get 'feedbacks/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users, skip: [:registrations, :passwords, :confirmations, :unlocks, :omniauth_callbacks, :mailers, :rememberable], controllers: {
    sessions: 'admin_users/sessions',
  }

  devise_for :users, skip: [:confirmations, :unlocks, :omniauth_callbacks]

  root 'quiz_sets#index'
  resources :quiz_sets, only: [:index, :show] do
    member do
      post 'start_quiz'
      get 'score'
    end
    resources :quizzes, only: [:show] do
      member do
        post 'answer'
        get 'explanation'
      end
    end
  end

  resources :weak_quizzes, only: [:show] do
    collection do
      get 'start'
      post 'start_quiz'
      get 'score'
    end
    member do
      post 'answer'
      get 'explanation'
    end
  end

  resources :quizzes, only: [:index] do
    collection do
      get 'search'
    end
  end

  resource :mypages, only: [] do
    collection do
      get 'profile'
      get 'scores'
      patch 'update_profile'
    end
  end

  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'

  namespace :api do
    resources :ratings, only: [:create]
    get 'ratings', to: 'ratings#show'
    resources :quiz_sets, only: [:index]
  end

  resources :feedbacks, only: [:create]
end

app/views/layouts/_footer.html.erb
<footer class="bg-gray-800 text-white py-6 px-8 mt-12">
  <div class="container mx-auto text-center text-sm md:text-base">
    <div class="mt-2">
      <%= link_to '利用規約', terms_path, class: "ml-4" %>
      <%= link_to 'プライバシーポリシー', privacy_path, class: "ml-4" %>
      <%= link_to 'お問い合わせ', 'https://forms.gle/toFZwS4vo9P5N4tm9', class: "ml-4" %>
    </div>
    <p class="mt-4">&copy; 2023 クイズ！市販薬の成分</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="<%= header_class.present? ? header_class : 'bg-blue-600' %> relative text-white px-2 lg:px-8 h-full">
  <div class="flex flex-wrap mx-auto items-center items-stretch">
  	
    <%#= #ダミー要素（スマホ画面でのみ表示） %>
    <div class="md:hidden text-white p-2">
      <svg class="h-6 w-6 opacity-0" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path>
      </svg>
    </div>

    <div class="flex-shrink-0 text-xl sm:text-2xl md:text-2xl lg:text-4xl font-bold text-center sm:text-left flex-grow py-2 md:py-4">
      <%= link_to 'クイズ！市販薬の成分', root_path, class: "clickable-text" %>
    </div>

    <button class="md:hidden text-white p-2" id="hamburger-button">
      <svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
      </svg>
    </button>

    <div class="flex-shrink-0 hidden md:flex items-center">
      <% if user_signed_in? %>

        <%= link_to '#', method: :get, class: "transition duration-300 ease-in-out flex items-center h-full group border-b-8 border-transparent hover:border-current p-2 text-white text-xs md:text-sm lg:text-base font-medium", id: "mega-menu-button-pc" do %>
          <i class="fa-solid fa-layer-group mr-1.5"></i>
          ジャンル一覧
        <% end %>
        <%= link_to quizzes_path, method: :get, class: "transition duration-300 ease-in-out flex items-center h-full group border-b-8 border-transparent hover:border-current p-2 text-white text-xs md:text-sm lg:text-base font-medium ml-3 lg:ml-5" do %>
          <i class="fa-solid fa-magnifying-glass mr-1.5"></i>
          クイズ検索
        <% end %>
        <%= link_to scores_mypages_path, method: :get, class: "transition duration-300 ease-in-out flex items-center h-full group border-b-8 border-transparent hover:border-current p-2 text-white text-xs md:text-sm lg:text-base font-medium ml-3 lg:ml-5" do %>
          <i class="fa-regular fa-rectangle-list mr-1.5"></i>
          スコアページ
        <% end %>
        <%= link_to profile_mypages_path, method: :get, class: "transition duration-300 ease-in-out flex items-center h-full group border-b-8 border-transparent hover:border-current p-2 text-white text-xs md:text-sm lg:text-base font-medium ml-3 lg:ml-5" do %>
          <i class="fa-solid fa-user-pen mr-1.5"></i>
          ユーザー情報編集
        <% end %>
        <%= link_to destroy_user_session_path, method: :get, class: "transition duration-300 ease-in-out flex items-center h-full group border-b-8 border-transparent hover:border-current p-2 text-white text-xs md:text-sm lg:text-base font-medium ml-3 lg:ml-5" do %>
          <i class="fa-solid fa-right-from-bracket mr-1.5"></i>
          ログアウト
        <% end %>
      <% else %>
        <%= link_to new_user_registration_path, method: :get, class: "transition duration-300 ease-in-out flex items-center h-full group border-b-8 border-transparent hover:border-current p-2 text-white text-xs md:text-sm lg:text-base font-medium ml-4 md:ml-6" do %>
          <i class="fa-regular fa-address-card mr-2"></i>
          会員登録
        <% end %>
        <%= link_to new_user_session_path, method: :get, class: "transition duration-300 ease-in-out flex items-center h-full group border-b-8 border-transparent hover:border-current p-2 text-white text-xs md:text-sm lg:text-base font-medium ml-4 md:ml-6" do %>
          <i class="fa-solid fa-right-to-bracket mr-2"></i>
          ログイン
        <% end %>
      <% end %>
    </div>

  </div>
  <div id="header-container" data-user-signed-in="<%= user_signed_in?.to_json %>"></div>
</header>

<script src="/assets/header.js"></script>

app/views/layouts/_quiz_header.html.erb
<header class="bg-blue-500 text-white py-3 px-6">
  <div class="container mx-auto text-center">
    <p class="text-lg md:text-xl font-bold">クイズ！市販薬の成分</p>
    <p class="text-lg md:text-xl tracking-wider mt-2"><%= @quiz_set.title %></p>
  </div>
</header>

app/views/layouts/_weak_quizzes_header.html.erb
<header class="bg-green-500 text-white py-3 px-6">
  <div class="container mx-auto text-center">
    <p class="text-lg md:text-xl font-bold">クイズ！市販薬の成分</p>
    <p class="text-md md:text-xl mt-2">苦手克服チャレンジ</p>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=<%= ENV["GA_TRACKING_ID"] %>"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'G-LYBGCQCQ68');
    </script>
    <script src="https://kit.fontawesome.com/85e6a48782.js" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'drugicon.ico' %>
    <%= display_meta_tags %>
    <meta name="csrf-token" content="<%= form_authenticity_token %>">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", media: 'all' %>
    <%= stylesheet_link_tag 'application.tailwind', "data-turbo-track": "reload", media: 'all' %>

    <link rel="preload" href="<%= asset_path('mainback1.webp') %>" as="image">
    <link rel="preload" href="<%= asset_path('mainback2.webp') %>" as="image">

    <style>
      body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        background-color: #f9fafb;
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
      }
      :root {
        --mainback1-path: url('<%= asset_path('mainback1.webp') %>');
        --mainback2-path: url('<%= asset_path('mainback2.webp') %>');
      }
    </style>

    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@arataqpp">
    <meta name="twitter:title" content="クイズ！市販薬の成分">
    <meta name="twitter:description" content="市販薬の成分を、クイズ形式で楽しく知って学べるサービスです。">
    <meta name="twitter:image" content="<%= image_url('quiz_top.jpg') %>">
  </head>

  <body>
    <%= render 'layouts/header', header_class: @header_class %>

    <main class="flex-grow">
      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/quiz.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=<%= ENV["GA_TRACKING_ID"] %>"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-LYBGCQCQ68');
    </script>
    <script src="https://kit.fontawesome.com/85e6a48782.js" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'drugicon.ico' %>
    <%= display_meta_tags %>
    <meta name="csrf-token" content="<%= form_authenticity_token %>">

    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application.tailwind', media: 'all', 'data-turbo-track': 'reload' %>

    <style>
      body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        background-color: #f9fafb;
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
      }
      :root {
        --mainback1-path: url('<%= asset_path('mainback1.webp') %>');
      }
    </style>
  </head>

  <body>
    <%= render 'layouts/quiz_header' %>
    <main class="flex-grow">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/weak_quizzes.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=<%= ENV["GA_TRACKING_ID"] %>"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'G-LYBGCQCQ68');
    </script>
    <script src="https://kit.fontawesome.com/85e6a48782.js" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'drugicon.ico' %>
    <%= display_meta_tags %>
    <meta name="csrf-token" content="<%= form_authenticity_token %>">

    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application.tailwind', media: 'all', 'data-turbo-track': 'reload' %>

    <style>
      body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        background-color: #f9fafb;
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
      }
      :root {
        --mainback1-path: url('<%= asset_path('mainback1.webp') %>');
      }
    </style>
  </head>

  <body>
    <%= render 'layouts/weak_quizzes_header' %>
    <main class="flex-grow">
      <%= yield %>
    </main>
    <%= yield :footer %>
  </body>
</html>